# Monokai Pro inspired
background = #2D2A2E
foreground = #FCFCFA
cursor-color = #FFD866
selection-background = #5B595C

palette = 0=#403E41
palette = 1=#FF6188
palette = 2=#A9DC76
palette = 3=#FFD866
palette = 4=#FC9867
palette = 5=#AB9DF2
palette = 6=#78DCE8
palette = 7=#FCFCFA

palette = 8=#727072
palette = 9=#FF6188
palette = 10=#A9DC76
palette = 11=#FFD866
palette = 12=#FC9867
palette = 13=#AB9DF2
palette = 14=#78DCE8
palette = 15=#FFFFFF

